
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO Z40-75
 */
public class frameMain extends javax.swing.JFrame {

    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labeltanggal = new javax.swing.JLabel();
        labelKasir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtdiskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnsave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtID = new javax.swing.JLabel();
        txtBarang = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkasir = new javax.swing.JTextField();
        ctanggal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        TAhasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setText("TOKO BUKU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 20, 330, 60);

        jLabel2.setText("Jl.Cokroaminoto No.112 Kota Blitar Kode Pos 66152");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 80, 380, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1140, 120);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        labeltanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labeltanggal.setText("Tanggal transaksi");
        jPanel2.add(labeltanggal);
        labeltanggal.setBounds(40, 30, 210, 30);

        labelKasir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelKasir.setText("Kasir : Ritza Kufita");
        jPanel2.add(labelKasir);
        labelKasir.setBounds(40, 70, 150, 22);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(null);
        jPanel3.add(txtid);
        txtid.setBounds(190, 110, 300, 26);
        jPanel3.add(txtnama);
        txtnama.setBounds(190, 160, 300, 26);

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel3.add(txtharga);
        txtharga.setBounds(190, 210, 300, 26);

        txtdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiskonActionPerformed(evt);
            }
        });
        jPanel3.add(txtdiskon);
        txtdiskon.setBounds(190, 260, 300, 26);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Kasir", "id barang", "nama brg", "harga ", "diskon", "total"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(520, 0, 590, 320);

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave);
        btnsave.setBounds(520, 350, 100, 29);

        btnDelete.setText("DELETE");
        jPanel3.add(btnDelete);
        btnDelete.setBounds(640, 350, 100, 29);

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(760, 350, 100, 29);

        jButton4.setText("REFRESH");
        jPanel3.add(jButton4);
        jButton4.setBounds(880, 350, 100, 29);

        jButton5.setText("EDIT");
        jPanel3.add(jButton5);
        jButton5.setBounds(1000, 350, 90, 29);

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.setText("ID barang");
        jPanel3.add(txtID);
        txtID.setBounds(30, 100, 140, 30);

        txtBarang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBarang.setText("Nama barang");
        jPanel3.add(txtBarang);
        txtBarang.setBounds(30, 140, 160, 40);

        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHarga.setText("Harga barang");
        jPanel3.add(txtHarga);
        txtHarga.setBounds(30, 190, 120, 40);

        txtDiskon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDiskon.setText("Diskon %");
        jPanel3.add(txtDiskon);
        txtDiskon.setBounds(30, 250, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tanggal Trans");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 10, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nama Kasir");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 60, 110, 22);

        txtkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkasirActionPerformed(evt);
            }
        });
        jPanel3.add(txtkasir);
        txtkasir.setBounds(190, 60, 300, 26);
        jPanel3.add(ctanggal);
        ctanggal.setBounds(190, 10, 300, 26);

        jLabel5.setText("TOTAL");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 330, 80, 20);

        TAhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAhasilActionPerformed(evt);
            }
        });
        jPanel3.add(TAhasil);
        TAhasil.setBounds(190, 310, 300, 90);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 120, 1110, 420);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 1140, 570);

        setBounds(0, 0, 1156, 754);
    }// </editor-fold>//GEN-END:initComponents

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiskonActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(ctanggal.getDate());
        int dskn = Integer.parseInt(txtdiskon.getText());
        int harga = Integer.parseInt(txtharga.getText());
        int hasil = harga*dskn/100;
        int total = harga-hasil;
        
        TAhasil.append("Total Harga : " + total+"\n");
        
        if ("".equals(tanggal) || 
                "".equals(txtkasir.getText()) ||
                "".equals(txtid.getText()) || 
                "".equals(txtnama) ||               
                "".equals(txtharga.getText()) || 
                "".equals(txtdiskon.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", 
            JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO t_toko (tanggal,kasir,id_barang,nama_barang,harga_barang,diskon,total) "
            + "VALUES('" + tanggal 
                    +"','" + txtkasir.getText() 
                    +"','" + txtid.getText() 
                    +"','" + txtnama.getText() 
                    +"','" + txtharga.getText()
                    +"','" + txtdiskon.getText()
                    +"','" + TAhasil.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }                                      

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            String id = tblData.getValueAt(baris, 2).toString();
            String SQL = "DELETE FROM t_toko WHERE id_barang='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkasirActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat=null;
            try {
                dateFormat=date.parse(tblData.getValueAt(baris, 0).toString());
            } catch (ParseException ex) {
                
            }
            ctanggal.setDate(dateFormat);
            txtkasir.setText(tblData.getValueAt(baris, 1).toString());
            txtid.setText(tblData.getValueAt(baris, 2).toString());            
            txtnama.setText(tblData.getValueAt(baris, 3).toString());
            txtharga.setText(tblData.getValueAt(baris, 4).toString());
            txtdiskon.setText(tblData.getValueAt(baris, 5).toString());
            TAhasil.setText(tblData.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void TAhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAhasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TAhasil;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnsave;
    private com.toedter.calendar.JDateChooser ctanggal;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKasir;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel txtBarang;
    private javax.swing.JLabel txtDiskon;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkasir;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    private void setTanggal() {
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    labeltanggal.setText(kal.format(skrg));
    }

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
